---
title: "Create Mortality Table"
author: "Eugenio Paglino"
output: html_document
---

```{r, echo=F, include=F}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r}
# Loading necessary packages
library(glue)
library(lubridate)
library(here)
library(colorspace)
library(patchwork)
library(gt)
library(ggh4x)
library(tidyverse)

# Set seed for the Rmd
set.seed(42)
```

```{r}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running
rm(list=ls())

i_am('R/decompose.Rmd')

inDir <- here('data','input')
outDir <- here('data','output')
figDir <- here('figures')
```

```{r}
mortData <- read_csv(here(outDir,'mortDataClean.csv'))
```

```{r}
create_add_data <- function(data,baseline,targetGroup) {
  
  addData <- data %>%
    filter(group %in% c(baseline,targetGroup)) %>%
    summarise(across(c(deaths,pop), ~ sum(.x)),
              .by=-c(group,deaths,pop)) %>%
    mutate(group=targetGroup,
           type='add')
  
  addData
}

create_sub_data <- function(data,baseline,targetGroup) {
  
  subData <- data %>%
    filter(group != targetGroup) %>%
    summarise(across(c(deaths,pop), ~ sum(.x)),
              .by=-c(group,deaths,pop)) %>%
    mutate(group=targetGroup,
           type='sub')
  
  subData
}
```

```{r}
# The data has to be formatted in the following way. The column with the
# groups has to be named group, the column with the starting age for each
# interval has to be named
format_data <- function(data,baseline) {
  
  groups <- data %>% filter(group!=baseline) %>% pull(group) %>% unique()

  addData <- map_dfr(groups,~create_add_data(data,baseline,.x))
  subData <- map_dfr(groups,~create_sub_data(data,baseline,.x))
  
  totalData <- data %>%
    summarise(across(c(deaths,pop), ~ sum(.x)),
              .by=-c(group,deaths,pop)) %>%
    mutate(group='Total',
           type='total')
  
  baselineData <- data %>%
    filter(group == baseline) %>%
    mutate(group=baseline,
           type='baseline')
  
  formattedData <- data %>% 
    filter(group!=baseline) %>%
    mutate(type='single') %>%
    add_row(baselineData) %>%
    add_row(addData) %>%
    add_row(subData) %>%
    add_row(totalData)
  
  formattedData
  
}
```

```{r}
prepare_data_for_lt <- function(data) {
  data <- data %>%
    arrange(x) %>%
    select(x,
           nDx=deaths,
           nNx=pop) %>%
    mutate(n=dplyr::lead(x) - x,
           n=if_else(x==85,Inf,n),
           nmx=nDx/nNx)
  data
}
```

```{r}
default_nax <- function(life_table,first_year_m,sex) {
  x = life_table['x']
  n = life_table['n']
  nmx = life_table['nmx']
  
  if (x == 0) {
    if (sex=='Male') {
      if (first_year_m >= 0.107) {
          return(0.330)
      } else {
        return(0.045 + 2.684*first_year_m)
      }
    } else if (sex=='Female') {
      if (first_year_m >= 0.107) {
        return(0.350)  
      } else {
        return(0.053 + 2.800*first_year_m)
      }
    }
  } else if (x == 1) {
    if (sex=='Male') {
      if (first_year_m >= 0.107) {
          return(1.352)
      } else {
        return(1.651 - 2.816*first_year_m)
      }
    } else if (sex=='Female') {
      if (first_year_m >= 0.107) {
        return(1.361)  
      } else {
        return(1.522 - 1.518*first_year_m)
      }
    }
  } else if (x>1 & is.finite(n)) {
    return(n/2)
  } else if (is.infinite(n)) {
    return(1/nmx)
  }
}
```

```{r}
keyfitz_graduation <- function(lt, .n=5, tol=0.0001) {
  naxold <- lt %>% pull(nax)
  diff <- Inf
  N <- nrow(lt) # Number of age groups 
  # Iterate until no nax changes by more than tol between iterations
  while(diff > 0.0001) {
    naxnew <- (-.n/24 * lag(lt$ndx) + .n/2 * lt$ndx + .n/24 * lead(lt$ndx)) / lt$ndx
	  naxnew <- c(naxold[1:2], naxnew[c(-1,-2,-N)], (1/lt$nmx)[N])
	  diff <- max(naxnew - naxold, na.rm=TRUE)
    naxold <- naxnew
    lt <- lt %>% mutate(nax = naxnew)
    lt <- m_to_q_conversion(lt)
  }
  lt
}
```

```{r}
q_from_m <- function(m,a,n) {
  numerator <- n*m
  denominator <- 1 + (n-a)*m
  nqx <- numerator/denominator
  nqx <- if_else(is.infinite(n),1,nqx)
  return(nqx)
}
```

```{r}
m_to_q_conversion <- function(lt,radix=100000,compute_nqx=T) {
  
  if (compute_nqx) {
    lt <- lt %>%
      mutate(nqx = q_from_m(nmx,nax,n))
  }
  
  lt <- lt %>%
    mutate(
      npx = 1-nqx,
      lx = lag(radix*cumprod(npx)),
      lx = if_else(is.na(lx),radix,lx),
      ndx=nqx*lx
      ) 
  lt
}
```

```{r}
create_life_table <- function(data,radix=100000,graduation=F,ltS=NULL,group=NULL) { 
  
  sex = data %>% pull(sex) %>% .[1]
  
  data <- prepare_data_for_lt(data)
  
  lt <- data %>%
    mutate(
      nax = apply(
      data,
      M=1,
      default_nax,
      first_year_m=as.double(data[1,'nmx']),
      sex=sex
      )
    )
    
  lt <- m_to_q_conversion(lt)
  
  if (graduation) lt <- keyfitz_graduation(lt)
  
  lt <- m_to_q_conversion(lt,compute_nqx=F)
  
  lt <- lt %>%
    mutate(
      nLx=(n*npx + nax*nqx)*lx,
      nLx=if_else(is.infinite(n),lx/nmx,nLx),
      Tx=rev(cumsum(rev(nLx))),
      ex=Tx/lx
      )
  
  lt
}
```

```{r}
compute_add_contribs <- function(data) {
  
  baselineData <- data %>%
    filter(type=='baseline') %>%
    select(sex,year,ltvar) %>%
    rename(baseline=ltvar)
  
  addContribs <- data %>%
    filter(type=='add') %>%
    left_join(baselineData,by=c('sex','year')) %>%
    mutate(contrib = ltvar - baseline)
  
  addContribs
  
}

compute_sub_contribs <- function(data) {
  
  totalData <- data %>%
    filter(type=='total') %>%
    select(sex,year,ltvar) %>%
    rename(total=ltvar)
  
  subContribs <- data %>%
    filter(type=='sub') %>%
    left_join(totalData,by=c('sex','year')) %>%
    mutate(contrib = total - ltvar)
  
  subContribs
  
}

compute_avg_contribs <- function(data) {
  
  addContribs <- compute_add_contribs(data) %>% select(-type)
  subContribs <- compute_sub_contribs(data) %>% select(-type)
  
  avgContribs <- addContribs %>%
    rename(addContrib = contrib,
           ltvarAdd = ltvar) %>%
    left_join(subContribs,by=c('sex','year','group')) %>%
    rename(subContrib = contrib,
           ltvarSub = ltvar) %>%
    mutate(avgContrib = (addContrib+subContrib)/2) %>%
    relocate(baseline,ltvarAdd,ltvarSub,total,
             addContrib,subContrib,avgContrib,
             .after=group)
    
  avgContribs
  
}

compute_discrepancy <- function(data) {
  
  avgContribs <- compute_avg_contribs(data)
  
  discrepancyData <- avgContribs %>%
    group_by(sex,year) %>%
    summarise(actual = min(total) - min(baseline),
              approx = sum(avgContrib)) %>%
    ungroup() %>%
    mutate(bias = actual-approx)
  
  discrepancyData
  
}

compute_adj_contribs <- function(data) {
  
  avgContribs <- compute_avg_contribs(data)
  discrepancyData <- compute_discrepancy(data)
  
  ngroups = length(unique(avgContribs$group))
  
  adjAvgContribs <- avgContribs %>%
    left_join(discrepancyData,by=c('sex','year')) %>%
    mutate(avgContribAdj=avgContrib+bias/ngroups)
  
  adjAvgContribs
  
}
```

```{r}
mortDataFormatted <- mortData %>%
  #filter(urbanization %in% c('Large Central Metro','Medium Metro','Small Metro','Micropolitan (Nonmetro)','NonCore (Nonmetro)')) %>%
  select(
    group=urbanization,
    sex,
    year,
    x=startAge,
    deaths,
    pop
    )
```

```{r}
formattedData <- format_data(mortDataFormatted,'Large Central Metro')
```

```{r}
groupedData <- formattedData %>%
  mutate(group=paste(sex,year,group,type,sep='-')) %>%
  group_by(group) %>%
  nest()
```

```{r}
lifeTables <- map2(
  groupedData$data,
  groupedData$group,
  ~ create_life_table(.x,graduation=F) %>%
    mutate(group=.y)
  )

names(lifeTables) <- groupedData$group
```

```{r}
e0Data <- groupedData %>%
  select(-data) %>%
  ungroup() %>%
  mutate(e0 = as.numeric(map(lifeTables,~ as.double(.x[1,'ex'])))) %>%
  separate(group,into=c('sex','year','group','type'),sep = '-') %>%
  mutate(year = as.integer(year)) %>%
  mutate(group=factor(group,
                      levels=c('Large Central Metro','Large Fringe Metro',
                               'Medium Metro','Small Metro',
                               'Micropolitan (Nonmetro)','NonCore (Nonmetro)')))
```

```{r}
LEByMetro <- e0Data %>%
  filter(type %in% c('baseline','single')) %>%
  ggplot() +
  geom_line(mapping=aes(x=year,y=e0,color=group,linetype=sex),linewidth=0.8) +
  geom_point(mapping=aes(x=year,y=e0,color=group,group=sex),shape=21,fill='white',size=2) +
  scale_color_discrete_sequential(palette='SunsetDark') +
  scale_x_continuous(breaks=c(2017,2018,2019)) +
  labs(x='Year',
       y='Life Expectancy at Birth',
       color='Urban-Rural',
       linetype='Sex') +
  theme_bw()

LEByMetro
```

```{r}
ggsave(here(figDir,'LEByMetro.png'),LEByMetro,height = 3, width = 7)
```

```{r}
contributions <- e0Data %>% 
  rename(ltvar=e0) %>%
  compute_adj_contribs()
```

```{r}
avgContribsFormatted %>%
  pivot_wider(names_from = sex, values_from = tempex124:tempex1Inf) %>%
  group_by(raceEthnicity) %>%
  select(
    raceEthnicity,
    year,
    tempex124_Female,
    tempex2564_Female,
    tempex65Inf_Female,
    tempex1Inf_Female,
    tempex124_Male,
    tempex2564_Male,
    tempex65Inf_Male,
    tempex1Inf_Male
    ) %>%
  gt() %>%
  cols_label(
    raceEthnicity='',
    year='Year',
    tempex124_Female = '1-24',
    tempex2564_Female = '25-64',
    tempex65Inf_Female = '65+',
    tempex1Inf_Female = '1+',
    tempex124_Male = '1-24',
    tempex2564_Male = '25-64',
    tempex65Inf_Male = '65+',
    tempex1Inf_Male = '1+'
    ) %>%
  fmt_number(
    columns = tempex124_Female:tempex1Inf_Male,
    decimals = 3
  ) %>%
  tab_spanner(
    label = 'Females',
    columns = tempex124_Female:tempex1Inf_Female
  ) %>%  
  tab_spanner(
    label = 'Males',
    columns = tempex124_Male:tempex1Inf_Male
  ) %>%  
  tab_spanner(
    label = 'Foreign-Born Contributions to Expected Years Lived in the Age Interval for the US Population',
    columns = tempex124_Female:tempex1Inf_Male
  ) %>%  
  cols_width(
    everything() ~ px(90)
    ) %>%
  gtsave(here('figures','contributions.png'),
       vwidth = 1000,vheight = 2000,zoom=4)
```

```{r}
withinContribs %>%
  write_csv(.,here(outDir,'withinContribs.csv'))

avgContribsFormatted %>%
  write_csv(.,here(outDir,'avgContribsFormatted.csv'))
```

```{r}
exactContribs <- tibble(
  contrib=c(0.276399366,-0.268115868,-0.223638258,
            -0.398612911,-0.354539651),
  group=c('Large Fringe Metro','Medium Metro','Small Metro',
          'Micropolitan (Nonmetro)','NonCore (Nonmetro)'),
  contribType=factor('Exact')
)

contribFormattedData <- contributions %>%
  select(year,sex,group,avgContrib,avgContribAdj) %>%
  pivot_longer(avgContrib:avgContribAdj,names_to = 'contribType',values_to = 'contrib') %>%
  mutate(contribType=factor(
    if_else(contribType=='avgContrib','Unadjusted','Adjusted'),
    levels=c('Unadjusted','Adjusted')
    ))

evalData <- contribFormattedData %>%
  filter(year==2017,sex=='Male') %>%
  select(group,contribType,contrib) %>%
  add_row(exactContribs) %>%
  mutate(contribType=relevel(contribType,'Unadjusted','Adjusted','Exact'))
  
```

```{r}
contribsPlots <- contribFormattedData %>%
  filter(contribType=='Unadjusted') %>%
  ggplot() +
  geom_col(mapping=aes(x=year,y=contrib,fill=group)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  facet_nested(~sex) +
  labs(x='',
       fill='',
       y='Non-Large Metro Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90))

contribsPlots
```

```{r}
ggsave(here(figDir,'contribsPlots.png'),contribsPlots,width = 4,height = 4)
```

```{r}
evalPlot <- evalData %>%
  ggplot() +
  geom_col(mapping=aes(x=contribType,y=contrib,fill=group)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  labs(x='',
       fill='',
       y='Non-Large Metro Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90))

evalPlot
```

```{r}
ggsave(here(figDir,'evalPlot.png'),evalPlot,width = 3.2,height = 4.5)
```

```{r}
adjContribsPlots <- contribFormattedData %>%
  ggplot() +
  geom_col(mapping=aes(x=contribType,y=contrib,fill=group)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  facet_nested(~sex+year) +
  labs(x='',
       fill='',
       y='Non-Large Metro Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90))

adjContribsPlots
```

```{r}
ggsave(here(figDir,'adjContribsPlots.png'),adjContribsPlots,height = 4,width=6)
```

```{r}
pdf(here(figDir,'RSContribPlotsSing.pdf'), width = 8, height = 5)
RSContribPlots
dev.off()
```

```{r}
RSContribPlotsUnstacked <- avgContribsFormatted %>%
  mutate(raceEthnicity=fct_relevel(raceEthnicity,
                                   'Hispanic','Asian','White','Black','Total')) %>%
  filter(raceEthnicity != 'Total') %>%
  ggplot() +
  geom_line(mapping=aes(x=year,y=tempex1Inf,color=raceEthnicity)) +
  scale_color_discrete_sequential(palette = 'viridis') +
  scale_x_continuous(breaks=2014:2021) +
  facet_wrap(~sex) +
  labs(x='',
       color='',
       y='Foreign-Born Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

RSContribPlotsUnstacked
```

```{r}
ggsave(here(figDir,'RSContribPlotsUnstackedSing.png'),RSContribPlotsUnstacked)
```

```{r}
pdf(here(figDir,'RSContribPlotsUnstackedSing.pdf'), width = 8, height = 8)
RSContribPlots / RSContribPlotsUnstacked + plot_annotation(tag_levels = 'A')
dev.off()
```

```{r}
contribPlots <- withinContribs %>%
  filter(ageRange=='tempex1Inf') %>%
  mutate(raceEthnicity=fct_relevel(raceEthnicity,
                                   'Hispanic','Asian','White','Black','Total')) %>%
  ggplot() +
  geom_col(mapping=aes(x=year,y=contribution,fill=raceEthnicity)) +
  scale_x_continuous(breaks=2014:2021) +
  scale_fill_discrete_sequential(palette = 'viridis') +
  facet_grid(sex~raceEthnicity) +
  labs(x='',
       fill='',
       y='Foreign-Born Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90),
        legend.position = 'bottom')

contribPlots
```

```{r}
ggsave(here(figDir,'contribPlotsSing.png'),contribPlots, width = 12, height = 5)
```

```{r}
pdf(here(figDir,'contribPlotsSing.pdf'), width = 12, height = 5)
contribPlots
dev.off()
```

```{r}
arriaga <- function(lt1,lt2,a) {
  lt1 <- lt1 %>% filter(x>=a)
  lt2 <- lt2 %>% filter(x>=a)
  N <- nrow(lt1)
  la <- lt1$lx[1]
  DE <- (lt1$lx/la) * (((lt2$Tx - lead(lt2$Tx))/lt2$lx) - ((lt1$Tx - lead(lt1$Tx))/lt1$lx)) 
  CS <- lt1$lx * (lead(lt2$lx)/lt2$lx) - lead(lt1$lx)
  IE <- (CS/la) * lead(lt1$ex)
  OE <- (CS/la) * lead(lt2$ex)
  I <- OE - IE 
  
  DE[N] <- (lt1$lx[N]/la) * (lt2$ex[N] - lt1$ex[N])
  IE[N] <- 0
  I[N] <- 0
  tot <- DE+IE+I
  
  group <- str_remove(lt1$group[1],'USB-')
  
  tibble(x=lt1$x,DE=DE,IE=IE,I=I,tot=tot,pct=tot/sum(tot),group=group)
}
```

```{r}
decompData <- map2_dfr(lifeTablesGradN,lifeTablesGradF,
                       ~ arriaga(.x,.y,a=1))
```

```{r}
decompDataFull <- decompData %>%
  separate_wider_delim(group, '-', names = c('raceEthnicity','sex', 'year')) %>%
  mutate(
    age=factor(
      case_when(
        x==0 ~ '<1',
        x==1 ~ '1-4',
        x==5 ~ '5-9',
        x==10 ~ '10-14',
        x==15 ~ '15-19',
        x==20 ~ '20-24',
        x==25 ~ '25-29',
        x==30 ~ '30-34',
        x==35 ~ '35-39',
        x==40 ~ '40-44',
        x==45 ~ '45-49',
        x==50 ~ '50-54',
        x==55 ~ '55-59',
        x==60 ~ '60-64',
        x==65 ~ '65-69',
        x==70 ~ '70-74',
        x==75 ~ '75-79',
        x==80 ~ '80-84',
        x==85 ~ '85-89',
        x==90 ~ '90+'
        )
      ),
    age=fct_relevel(age,'1-4','5-9'),
    raceEthnicity=fct_relevel(raceEthnicity,'Total','White','Black','Hispanic','Asian'))
```

```{r}
decompDataSummary <- decompData %>%
  separate_wider_delim(group, '-', names = c('raceEthnicity','sex', 'year')) %>%
  mutate(
    age=factor(
      case_when(
        between(x,0,24) ~ '0-24',
        between(x,25,64) ~ '25-64',
        between(x,65,Inf) ~ '65+',)
      ),
    age=fct_relevel(age,'0-24','25-64','65+'),
    raceEthnicity=fct_relevel(raceEthnicity,'Total','White','Black','Hispanic','Asian')) %>%
  group_by(year,age,sex,raceEthnicity) %>%
  summarise(contrib=sum(tot)) %>%
  ungroup()
```

```{r}
decompPlotMales <- decompDataSummary %>%
  filter(sex=='Male',
         raceEthnicity!='Other or Multiple Race') %>%
  ggplot() +
  geom_col(mapping=aes(x=age,y=contrib,fill=age)) +
  labs(x='Age',
       y='Contribution to Difference in Life-Expectancy\nbetween Foreign-Born and US-Born',
       fill='') +
  facet_grid(raceEthnicity ~ year) +
  coord_cartesian(ylim=c(-0.5,8)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=90),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank())

decompPlotMales
```

```{r}
ggsave(here(figDir,'decompPlotMalesSing.png'),decompPlotMales)
```

```{r}
pdf(here(figDir,'decompPlotMalesSing.pdf'), width = 12, height = 8)
decompPlotMales
dev.off()
```

```{r}
decompPlotFemales <- decompDataSummary %>%
  filter(sex=='Female',
         raceEthnicity!='Other or Multiple Race') %>%
  ggplot() +
  geom_col(mapping=aes(x=age,y=contrib,fill=age)) +
  labs(x='Age',
       y='Contribution to Difference in Life-Expectancy\nbetween Foreign-Born and US-Born',
       fill='') +
  facet_grid(raceEthnicity ~ year) +
  coord_cartesian(ylim=c(-0.5,8)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=90),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank())

decompPlotFemales
```

```{r}
ggsave(here(figDir,'decompPlotFemalesSing.png'),decompPlotFemales)
```

```{r}
pdf(here(figDir,'decompPlotFemalesSing.pdf'), width = 12, height = 8)
decompPlotFemales
dev.off()
```