---
title: "Create Mortality Table"
author: "Eugenio Paglino"
output: html_document
---

```{r, echo=F, include=F}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r}
# Loading necessary packages
library(glue)
library(lubridate)
library(here)
library(colorspace)
library(patchwork)
library(DemoTools)
library(DemoDecomp)
library(gt)
library(ggh4x)
library(tidyverse)

# Set seed for the Rmd
set.seed(42)
```

```{r}
# Do not rely on this to completely clean your environment
# Better to do a full restart of R before running
rm(list=ls())

i_am('R/decompose.Rmd')

inDir <- here('data','input')
outDir <- here('data','output')
figDir <- here('figures')
```

```{r}
mortData <- read_csv(here(outDir,'mortDataClean.csv'))
```

```{r}
mortDataByGroup <- mortData %>%
  rename(nNx=pop,nDx=deaths,group=urbanization) %>%
  group_by(year,sex) %>%
  nest()
```

```{r}
testData <- mortDataByGroup$data[[4]]
baseline <- 'Large Central Metro'
groups <- testData %>% pull(group)
ages <- testData %>% pull(ageGroup)

nNx1 <- testData %>%
  mutate(nNx=if_else(group==baseline,nNx,0)) %>%
  pull(nNx)

nDx1 <- testData %>%
  mutate(nDx=if_else(group==baseline,nDx,0)) %>%
  pull(nDx)

nNx2 <- testData %>%
  pull(nNx)

nDx2 <- testData %>%
  pull(nDx)
```

```{r}
total_e0 <- function(pars,groups,ages) {
  
  G <- length(unique(groups))
  A <- length(unique(ages))
  N <- G*A
  
  split_pars <- split(pars,rep(c('nNx','nDx'),each=N))
  nNx <- split_pars$nNx
  nDx <- split_pars$nDx
  
  lt_data <- tibble(
    nNx=nNx,
    nDx=nDx,
    group=groups,
    age=ages
  )
  
  nmx <- lt_data %>%
    group_by(age) %>%
    summarise(
      nNx=sum(nNx),
      nDx=sum(nDx)
      ) %>%
    ungroup() %>%
    mutate(nmx=nDx/nNx) %>%
    pull(nmx)
  
  e0 <- LTabr(nmx)
  
  e0
}
```

```{r}
total_e0(c(nNx2,nDx2),groups,ages) - total_e0(c(nNx1,nDx1),groups,ages) 
```

```{r}
# Decomposing this difference with the two methods
decomp <- tibble(
  age = rep(ages,2),
  group = rep(groups,2),
  pars1 = c(nNx1,nDx1),
  pars2 = c(nNx2,nDx2),
  C = horiuchi(
    func = total_e0,
    pars1 = pars1,
    pars2 = pars2,
    groups = groups,
    ages = ages,
    N=10
    )
)
```

```{r}
decomp %>%
  group_by(group) %>%
  summarise(C=sum(C)) %>%
  ungroup() %>%
  mutate(Ctot = sum(C))
```




```{r}
compute_add_contribs <- function(data) {
  
  baselineData <- data %>%
    filter(type=='baseline') %>%
    select(sex,year,ltvar) %>%
    rename(baseline=ltvar)
  
  addContribs <- data %>%
    filter(type=='add') %>%
    left_join(baselineData,by=c('sex','year')) %>%
    mutate(contrib = ltvar - baseline)
  
  addContribs
  
}

compute_sub_contribs <- function(data) {
  
  totalData <- data %>%
    filter(type=='total') %>%
    select(sex,year,ltvar) %>%
    rename(total=ltvar)
  
  subContribs <- data %>%
    filter(type=='sub') %>%
    left_join(totalData,by=c('sex','year')) %>%
    mutate(contrib = total - ltvar)
  
  subContribs
  
}

compute_avg_contribs <- function(data) {
  
  addContribs <- compute_add_contribs(data) %>% select(-type)
  subContribs <- compute_sub_contribs(data) %>% select(-type)
  
  avgContribs <- addContribs %>%
    rename(addContrib = contrib,
           ltvarAdd = ltvar) %>%
    left_join(subContribs,by=c('sex','year','group')) %>%
    rename(subContrib = contrib,
           ltvarSub = ltvar) %>%
    mutate(avgContrib = (addContrib+subContrib)/2) %>%
    relocate(baseline,ltvarAdd,ltvarSub,total,
             addContrib,subContrib,avgContrib,
             .after=group)
    
  avgContribs
  
}

compute_discrepancy <- function(data) {
  
  avgContribs <- compute_avg_contribs(data)
  
  discrepancyData <- avgContribs %>%
    group_by(sex,year) %>%
    summarise(actual = min(total) - min(baseline),
              approx = sum(avgContrib)) %>%
    ungroup() %>%
    mutate(bias = actual-approx)
  
  discrepancyData
  
}

compute_adj_contribs <- function(data) {
  
  avgContribs <- compute_avg_contribs(data)
  discrepancyData <- compute_discrepancy(data)
  
  ngroups = length(unique(avgContribs$group))
  
  adjAvgContribs <- avgContribs %>%
    left_join(discrepancyData,by=c('sex','year')) %>%
    mutate(avgContribAdj=avgContrib+bias/ngroups)
  
  adjAvgContribs
  
}
```

```{r}
mortDataFormatted <- mortData %>%
  #filter(urbanization %in% c('Large Central Metro','Medium Metro','Small Metro','Micropolitan (Nonmetro)','NonCore (Nonmetro)')) %>%
  select(
    group=urbanization,
    sex,
    year,
    x=startAge,
    deaths,
    pop
    )
```

```{r}
formattedData <- format_data(mortDataFormatted,'Large Central Metro')
```

```{r}
groupedData <- formattedData %>%
  mutate(group=paste(sex,year,group,type,sep='-')) %>%
  group_by(group) %>%
  nest()
```

```{r}
lifeTables <- map2(
  groupedData$data,
  groupedData$group,
  ~ create_life_table(.x,graduation=F) %>%
    mutate(group=.y)
  )

names(lifeTables) <- groupedData$group
```

```{r}
e0Data <- groupedData %>%
  select(-data) %>%
  ungroup() %>%
  mutate(e0 = as.numeric(map(lifeTables,~ as.double(.x[1,'ex'])))) %>%
  separate(group,into=c('sex','year','group','type'),sep = '-') %>%
  mutate(year = as.integer(year)) %>%
  mutate(group=factor(group,
                      levels=c('Large Central Metro','Large Fringe Metro',
                               'Medium Metro','Small Metro',
                               'Micropolitan (Nonmetro)','NonCore (Nonmetro)')))
```

```{r}
LEByMetro <- e0Data %>%
  filter(type %in% c('baseline','single')) %>%
  ggplot() +
  geom_line(mapping=aes(x=year,y=e0,color=group,linetype=sex),linewidth=0.8) +
  geom_point(mapping=aes(x=year,y=e0,color=group,group=sex),shape=21,fill='white',size=2) +
  scale_color_discrete_sequential(palette='SunsetDark') +
  scale_x_continuous(breaks=c(2017,2018,2019)) +
  labs(x='Year',
       y='Life Expectancy at Birth',
       color='Urban-Rural',
       linetype='Sex') +
  theme_bw()

LEByMetro
```

```{r}
ggsave(here(figDir,'LEByMetro.png'),LEByMetro,height = 3, width = 7)
```

```{r}
contributions <- e0Data %>% 
  rename(ltvar=e0) %>%
  compute_adj_contribs()
```

```{r}
avgContribsFormatted %>%
  pivot_wider(names_from = sex, values_from = tempex124:tempex1Inf) %>%
  group_by(raceEthnicity) %>%
  select(
    raceEthnicity,
    year,
    tempex124_Female,
    tempex2564_Female,
    tempex65Inf_Female,
    tempex1Inf_Female,
    tempex124_Male,
    tempex2564_Male,
    tempex65Inf_Male,
    tempex1Inf_Male
    ) %>%
  gt() %>%
  cols_label(
    raceEthnicity='',
    year='Year',
    tempex124_Female = '1-24',
    tempex2564_Female = '25-64',
    tempex65Inf_Female = '65+',
    tempex1Inf_Female = '1+',
    tempex124_Male = '1-24',
    tempex2564_Male = '25-64',
    tempex65Inf_Male = '65+',
    tempex1Inf_Male = '1+'
    ) %>%
  fmt_number(
    columns = tempex124_Female:tempex1Inf_Male,
    decimals = 3
  ) %>%
  tab_spanner(
    label = 'Females',
    columns = tempex124_Female:tempex1Inf_Female
  ) %>%  
  tab_spanner(
    label = 'Males',
    columns = tempex124_Male:tempex1Inf_Male
  ) %>%  
  tab_spanner(
    label = 'Foreign-Born Contributions to Expected Years Lived in the Age Interval for the US Population',
    columns = tempex124_Female:tempex1Inf_Male
  ) %>%  
  cols_width(
    everything() ~ px(90)
    ) %>%
  gtsave(here('figures','contributions.png'),
       vwidth = 1000,vheight = 2000,zoom=4)
```

```{r}
withinContribs %>%
  write_csv(.,here(outDir,'withinContribs.csv'))

avgContribsFormatted %>%
  write_csv(.,here(outDir,'avgContribsFormatted.csv'))
```

```{r}
exactContribs <- tibble(
  contrib=c(0.276399366,-0.268115868,-0.223638258,
            -0.398612911,-0.354539651),
  group=c('Large Fringe Metro','Medium Metro','Small Metro',
          'Micropolitan (Nonmetro)','NonCore (Nonmetro)'),
  contribType=factor('Exact')
)

contribFormattedData <- contributions %>%
  select(year,sex,group,avgContrib,avgContribAdj) %>%
  pivot_longer(avgContrib:avgContribAdj,names_to = 'contribType',values_to = 'contrib') %>%
  mutate(contribType=factor(
    if_else(contribType=='avgContrib','Unadjusted','Adjusted'),
    levels=c('Unadjusted','Adjusted')
    ))

evalData <- contribFormattedData %>%
  filter(year==2017,sex=='Male') %>%
  select(group,contribType,contrib) %>%
  add_row(exactContribs) %>%
  mutate(contribType=relevel(contribType,'Unadjusted','Adjusted','Exact'))
  
```

```{r}
contribsPlots <- contribFormattedData %>%
  filter(contribType=='Unadjusted') %>%
  ggplot() +
  geom_col(mapping=aes(x=year,y=contrib,fill=group)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  facet_nested(~sex) +
  labs(x='',
       fill='',
       y='Non-Large Metro Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90))

contribsPlots
```

```{r}
ggsave(here(figDir,'contribsPlots.png'),contribsPlots,width = 4,height = 4)
```

```{r}
evalPlot <- evalData %>%
  ggplot() +
  geom_col(mapping=aes(x=contribType,y=contrib,fill=group)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  labs(x='',
       fill='',
       y='Non-Large Metro Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90))

evalPlot
```

```{r}
ggsave(here(figDir,'evalPlot.png'),evalPlot,width = 3.2,height = 4.5)
```

```{r}
adjContribsPlots <- contribFormattedData %>%
  ggplot() +
  geom_col(mapping=aes(x=contribType,y=contrib,fill=group)) +
  scale_fill_discrete_sequential(palette = 'SunsetDark') +
  facet_nested(~sex+year) +
  labs(x='',
       fill='',
       y='Non-Large Metro Contribution to Life Expectancy') +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle=90))

adjContribsPlots
```

```{r}
ggsave(here(figDir,'adjContribsPlots.png'),adjContribsPlots,height = 4,width=6)
```
